# Generated by Django 6.1.1 on 2026-09-20 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='audio_preview',
            field=models.FileField(blank=True, null=True, upload_to='previews/'),
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='estilo',
            field=models.CharField(default='rock', max_length=50),
        ),
    ]
