# Generated by Django 6.1.1 on 2026-09-21 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_remove_producto_stock_alter_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen_derecha',
            field=models.ImageField(blank=True, null=True, upload_to='modales/'),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen_izquierda',
            field=models.ImageField(blank=True, null=True, upload_to='modales/'),
        ),
    ]
